version: 2

before:
  hooks:
    - go mod tidy
    - go install github.com/tc-hib/go-winres@latest
    - go generate ./...

release:
  # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦ä¸ºé¢„å‘å¸ƒç‰ˆæœ¬
  prerelease: auto

# å˜æ›´æ—¥å¿—é…ç½® (æ–°å¢žéƒ¨åˆ†)
changelog:
  # æŽ’åºæ–¹å¼ï¼šasc (æ—§->æ–°) æˆ– desc (æ–°->æ—§)
  sort: asc
  # ä½¿ç”¨ github è‡ªåŠ¨é“¾æŽ¥ issue å’Œå¤„ç†è´¡çŒ®è€…
  use: github
  # è¿‡æ»¤æŽ‰ä¸éœ€è¦æ˜¾ç¤ºåœ¨æ—¥å¿—ä¸­çš„æäº¤
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^style:"
      - "^Merge pull request"
      - "^Merge branch"
      - "go mod tidy"
  # æ ¼å¼
  format: "{{.SHA}}: {{.Message}}"
  # æäº¤åˆ†ç»„é…ç½®
  groups:
    - title: "âœ¨ æ–°åŠŸèƒ½"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "ðŸ› Bug ä¿®å¤"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "ðŸš€ æ€§èƒ½ä¼˜åŒ–"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "ðŸ”§ ç»´æŠ¤ä¸Žé‡æž„"
      regexp: "^.*(chore|refactor|build|ci)[(\\w)]*:+.*$"
      order: 3
    - title: "ðŸ“ æ–‡æ¡£"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 4
    - title: "å…¶ä»–"
      order: 999

# æž„å»ºé…ç½®
builds:
  - id: subs-check-pro
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc,jsonv2
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: "386"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.CurrentCommit={{ .ShortCommit }}

# å½’æ¡£é…ç½®
archives:
  - ids:
      - subs-check-pro
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv7
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: zip
