package platform

// Code generated by TestAggregateSpeedResults at 2025-11-17 03:49:10; 
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
        "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe", // avg: 6912.88 KB/s, samples: 10, errors: 1
        "https://updates.cdn-apple.com/2025FallFCS/fullrestores/089-12066/4F86CB11-E6FA-47CB-96A8-527A4CBD9273/iPhone18,3_26.1_23B85_Restore.ipsw", // avg: 6413.06 KB/s, samples: 11, errors: 1
        "http://updates-http.cdn-apple.com/2019WinterFCS/fullrestores/041-39257/32129B6C-292C-11E9-9E72-4511412B0A59/iPhone_4.7_12.1.4_16D57_Restore.ipsw", // avg: 3948.10 KB/s, samples: 11, errors: 1
        "https://speed.cloudflare.com/__down?bytes=1073741824", // avg: 3478.19 KB/s, samples: 10, errors: 1
        "http://hkg.download.datapacket.com/10000mb.bin", // avg: 3264.45 KB/s, samples: 10, errors: 2
        "https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi", // avg: 3036.60 KB/s, samples: 10, errors: 1
        "https://update.code.visualstudio.com/1.102.0/win32-x64-user/stable", // avg: 2988.54 KB/s, samples: 9, errors: 2
        "http://sgp.download.datapacket.com/1000mb.bin", // avg: 2973.13 KB/s, samples: 11, errors: 1
        "https://speed.cloudflare.com/__down?bytes=5368709120", // avg: 2606.47 KB/s, samples: 10, errors: 1
        "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-linux-x86_64.tar.gz", // avg: 2561.23 KB/s, samples: 11, errors: 1
        "http://tyo.download.datapacket.com/10000mb.bin", // avg: 2258.96 KB/s, samples: 10, errors: 1
        "https://cachefly.cachefly.net/300mb.test", // avg: 2143.48 KB/s, samples: 9, errors: 2
        "http://tyo.download.datapacket.com/100mb.bin", // avg: 2142.60 KB/s, samples: 11, errors: 1
        "http://sgp.download.datapacket.com/100mb.bin", // avg: 2109.97 KB/s, samples: 11, errors: 1
        "https://sgp.proof.ovh.net/files/100Mb.dat", // avg: 2098.64 KB/s, samples: 10, errors: 2
        "http://ash.download.datapacket.com/10000mb.bin", // avg: 2015.86 KB/s, samples: 10, errors: 2
        "http://sgp.download.datapacket.com/10000mb.bin", // avg: 1978.56 KB/s, samples: 11, errors: 1
        "http://lax.download.datapacket.com/10000mb.bin", // avg: 1957.46 KB/s, samples: 10, errors: 1
        "http://lax.download.datapacket.com/100mb.bin", // avg: 1953.07 KB/s, samples: 11, errors: 0
        "https://sgp.proof.ovh.net/files/1Gb.dat", // avg: 1945.46 KB/s, samples: 10, errors: 2
        "http://ash.download.datapacket.com/100mb.bin", // avg: 1936.02 KB/s, samples: 10, errors: 2
        "https://static.rust-lang.org/dist/rust-1.83.0-x86_64-unknown-linux-gnu.tar.gz", // avg: 1838.65 KB/s, samples: 9, errors: 2
        "http://ash.download.datapacket.com/1000mb.bin", // avg: 1834.02 KB/s, samples: 10, errors: 2
        "http://lax.download.datapacket.com/1000mb.bin", // avg: 1777.71 KB/s, samples: 11, errors: 0
        "http://hkg.download.datapacket.com/1000mb.bin", // avg: 1760.01 KB/s, samples: 10, errors: 2
        "http://tyo.download.datapacket.com/1000mb.bin", // avg: 1567.81 KB/s, samples: 10, errors: 2
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-windows-x64.zip", // avg: 1563.83 KB/s, samples: 11, errors: 1
        "https://awscli.amazonaws.com/AWSCLIV2.msi", // avg: 1459.79 KB/s, samples: 9, errors: 2
        "https://github.com/mihomo-party-org/clash-party/releases/download/v1.8.8/mihomo-party-windows-1.8.8-x64-portable.7z", // avg: 1442.10 KB/s, samples: 6, errors: 5
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-linux-x64.tar.xz", // avg: 1371.51 KB/s, samples: 10, errors: 1
        "https://github.com/pytorch/pytorch/releases/download/v2.9.1/pytorch-v2.9.1.tar.gz", // avg: 1358.06 KB/s, samples: 9, errors: 2
        "http://hkg.download.datapacket.com/100mb.bin", // avg: 1353.96 KB/s, samples: 10, errors: 2
        "http://par.download.datapacket.com/10000mb.bin", // avg: 1305.88 KB/s, samples: 11, errors: 1
        "https://lax-ca-us-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1187.82 KB/s, samples: 8, errors: 3
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run", // avg: 1177.11 KB/s, samples: 7, errors: 4
        "http://par.download.datapacket.com/100mb.bin", // avg: 1160.78 KB/s, samples: 11, errors: 1
        "https://fra-de-ping.vultr.com/vultr.com.100MB.bin", // avg: 1053.06 KB/s, samples: 10, errors: 2
}
