package platform

// Code generated by TestAggregateSpeedResults at 2026-01-18 15:15:45; 
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
        "https://updates.cdn-apple.com/2025FallFCS/fullrestores/089-12066/4F86CB11-E6FA-47CB-96A8-527A4CBD9273/iPhone18,3_26.1_23B85_Restore.ipsw", // avg: 6744.56 KB/s, samples: 21, errors: 6
        "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe", // avg: 4691.71 KB/s, samples: 17, errors: 9
        "http://updates-http.cdn-apple.com/2019WinterFCS/fullrestores/041-39257/32129B6C-292C-11E9-9E72-4511412B0A59/iPhone_4.7_12.1.4_16D57_Restore.ipsw", // avg: 3753.07 KB/s, samples: 21, errors: 6
        "http://sgp.download.datapacket.com/1000mb.bin", // avg: 2602.59 KB/s, samples: 24, errors: 3
        "https://speed.cloudflare.com/__down?bytes=1073741824", // avg: 2534.14 KB/s, samples: 24, errors: 2
        "https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi", // avg: 2376.72 KB/s, samples: 25, errors: 2
        "https://update.code.visualstudio.com/1.102.0/win32-x64-user/stable", // avg: 2293.21 KB/s, samples: 22, errors: 6
        "http://sgp.download.datapacket.com/10000mb.bin", // avg: 2221.99 KB/s, samples: 24, errors: 3
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run", // avg: 2174.44 KB/s, samples: 14, errors: 12
        "http://sgp.download.datapacket.com/100mb.bin", // avg: 2028.61 KB/s, samples: 24, errors: 3
        "http://lax.download.datapacket.com/10000mb.bin", // avg: 1989.19 KB/s, samples: 22, errors: 4
        "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-linux-x86_64.tar.gz", // avg: 1831.33 KB/s, samples: 26, errors: 2
        "https://speed.cloudflare.com/__down?bytes=5368709120", // avg: 1793.19 KB/s, samples: 24, errors: 2
        "https://download-installer.cdn.mozilla.net/pub/firefox/releases/140.5.0esr/win64/en-US/Firefox%20Setup%20140.5.0esr.exe", // avg: 1728.91 KB/s, samples: 21, errors: 5
        "https://download-installer.cdn.mozilla.net/pub/firefox/releases/145.0/win64/en-US/Firefox%20Setup%20145.0.exe", // avg: 1670.51 KB/s, samples: 25, errors: 2
        "http://hkg.download.datapacket.com/10000mb.bin", // avg: 1655.02 KB/s, samples: 23, errors: 4
        "http://tyo.download.datapacket.com/100mb.bin", // avg: 1648.90 KB/s, samples: 24, errors: 3
        "https://awscli.amazonaws.com/AWSCLIV2.msi", // avg: 1623.84 KB/s, samples: 21, errors: 5
        "http://lax.download.datapacket.com/100mb.bin", // avg: 1577.52 KB/s, samples: 21, errors: 5
        "http://tyo.download.datapacket.com/10000mb.bin", // avg: 1576.83 KB/s, samples: 23, errors: 3
        "https://sgp.proof.ovh.net/files/1Gb.dat", // avg: 1483.54 KB/s, samples: 23, errors: 4
        "https://cachefly.cachefly.net/300mb.test", // avg: 1326.78 KB/s, samples: 21, errors: 5
        "https://sgp.proof.ovh.net/files/100Mb.dat", // avg: 1316.28 KB/s, samples: 22, errors: 5
        "https://sgp.proof.ovh.net/files/10Gb.dat", // avg: 1307.56 KB/s, samples: 23, errors: 4
        "http://hkg.download.datapacket.com/1000mb.bin", // avg: 1305.83 KB/s, samples: 22, errors: 5
        "http://lax.download.datapacket.com/1000mb.bin", // avg: 1263.49 KB/s, samples: 23, errors: 3
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-linux-x64.tar.xz", // avg: 1214.88 KB/s, samples: 23, errors: 3
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.85_windows.exe", // avg: 1211.10 KB/s, samples: 20, errors: 7
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-windows-x64.zip", // avg: 1205.90 KB/s, samples: 25, errors: 2
        "http://ash.download.datapacket.com/10000mb.bin", // avg: 1135.40 KB/s, samples: 23, errors: 4
        "http://ash.download.datapacket.com/1000mb.bin", // avg: 1116.58 KB/s, samples: 22, errors: 5
        "https://download.gimp.org/mirror/pub/gimp/v3.0/windows/gimp-3.0.0-setup.exe", // avg: 1105.85 KB/s, samples: 15, errors: 11
        "http://tyo.download.datapacket.com/1000mb.bin", // avg: 1100.23 KB/s, samples: 23, errors: 4
        "http://ash.download.datapacket.com/100mb.bin", // avg: 1083.30 KB/s, samples: 23, errors: 4
}
