package platform

// Code generated by TestAggregateSpeedResults at 2026-06-15 09:01:13; 
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
        "https://hkg.download.datapacket.com/1000mb.bin", // avg: 3620.78 KB/s, samples: 2, errors: 0
        "https://get.enterprisedb.com/postgresql/postgresql-16.3-1-windows-x64.exe", // avg: 2794.82 KB/s, samples: 2, errors: 0
        "https://awscli.amazonaws.com/AWSCLIV2.msi", // avg: 2663.57 KB/s, samples: 2, errors: 0
        "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe", // avg: 2493.78 KB/s, samples: 2, errors: 0
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run", // avg: 2265.24 KB/s, samples: 2, errors: 0
        "https://tyo.download.datapacket.com/1000mb.bin", // avg: 2254.36 KB/s, samples: 2, errors: 0
        "https://sgp.download.datapacket.com/1000mb.bin", // avg: 2193.31 KB/s, samples: 2, errors: 0
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.85_windows.exe", // avg: 2137.28 KB/s, samples: 2, errors: 0
        "https://ash.download.datapacket.com/1000mb.bin", // avg: 2117.26 KB/s, samples: 2, errors: 0
        "https://cachefly.cachefly.net/300mb.test", // avg: 2086.65 KB/s, samples: 2, errors: 0
        "https://fra-de-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1828.93 KB/s, samples: 2, errors: 0
        "https://sgp.proof.ovh.net/files/1Gb.dat", // avg: 1765.45 KB/s, samples: 2, errors: 0
        "https://hil.proof.ovh.us/files/1Gb.dat", // avg: 1734.20 KB/s, samples: 2, errors: 0
        "https://download.gimp.org/mirror/pub/gimp/v3.0/windows/gimp-3.0.0-setup.exe", // avg: 1674.55 KB/s, samples: 2, errors: 0
        "https://ash-speed.hetzner.com/1GB.bin", // avg: 1602.71 KB/s, samples: 2, errors: 0
        "https://lax-ca-us-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1601.14 KB/s, samples: 2, errors: 0
        "https://speedtest.fra1.hivelocity.net/10GiB.file", // avg: 1355.85 KB/s, samples: 2, errors: 0
        "https://par.download.datapacket.com/1000mb.bin", // avg: 1241.95 KB/s, samples: 2, errors: 0
        "https://static.rust-lang.org/dist/rust-1.83.0-x86_64-unknown-linux-gnu.tar.gz", // avg: 1235.68 KB/s, samples: 2, errors: 0
        "https://lax.download.datapacket.com/1000mb.bin", // avg: 1169.88 KB/s, samples: 2, errors: 0
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-linux-x64.tar.xz", // avg: 1070.68 KB/s, samples: 2, errors: 0
}
